services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_API_KEY=${CF_API_KEY}
    command:
    # Logs
      - --log.level=DEBUG
    # Dashboard
      - --api.dashboard=true
    #Providers
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/file_conf.yml
    #Entrypoints
      - --entryPoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=le_dns
    #ACME Config
      # - --certificatesresolvers.le_dns.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le_dns.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.le_dns.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le_dns.acme.dnschallenge=true
      - --certificatesresolvers.le_dns.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le_dns.acme.dnschallenge.propagation.delayBeforeChecks=120s
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./file_conf.yml:/file_conf.yml
      

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le_dns"       

networks:
  proxy:
    external: true