api:
  dashboard: true
  insecure: true
  # debug: false # Optional can be Enabled if needed for troubleshooting

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
      #  file:
      #    filename: "/file_conf/dynamic_conf.yml"
      #    watch: true

# log:
#   level: WARN
#   filePath: /logs/traefik.log

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  le_dns:
    acme:
      email: ${CF_API_EMAIL}
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 120

