api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/file_conf/dynamic_conf.yml"
    watch: true

log:
  filePath: "/logs/traefik.log"
  #  level: DEBUG

serversTransport:
  insecureSkipVerify: true
  #  rootCAs:
  #    - mccullonas_ca_root_cert.crt 

certificatesResolvers:
  le_dns:
    acme:
      email: "email@example.co.uk"
      storage: "/certs/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 120

